'use strict';

const fs = require('node:fs');
const path = require('node:path');

/**
 * Generate a static site from sprint output directory.
 * Creates an index.html that links to all artifacts with
 * a dark-themed navigation page.
 */

const TEMPLATE = (title, items) => `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
      background: #111;
      color: #e5e5e5;
      min-height: 100vh;
      padding: 2rem;
    }
    h1 {
      color: #d97706;
      font-size: 1.8rem;
      margin-bottom: 0.5rem;
    }
    .subtitle {
      color: #888;
      margin-bottom: 2rem;
      font-size: 0.9rem;
    }
    .artifacts {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
      gap: 1rem;
    }
    .card {
      background: #1a1a1a;
      border: 1px solid #333;
      border-radius: 8px;
      padding: 1.2rem;
      transition: border-color 0.2s;
    }
    .card:hover { border-color: #d97706; }
    .card a {
      color: #d97706;
      text-decoration: none;
      font-weight: 600;
      font-size: 1.05rem;
    }
    .card a:hover { text-decoration: underline; }
    .card .meta {
      color: #888;
      font-size: 0.8rem;
      margin-top: 0.4rem;
    }
    footer {
      margin-top: 3rem;
      color: #555;
      font-size: 0.75rem;
      text-align: center;
    }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <p class="subtitle">Generated by mill</p>
  <div class="artifacts">
    ${items}
  </div>
  <footer>Built with @grainulator/mill</footer>
</body>
</html>
`;

function formatBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function scanDir(dir, base) {
  const entries = [];
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    const stat = fs.statSync(full);
    if (stat.isFile() && !name.startsWith('.')) {
      const rel = path.relative(base, full);
      entries.push({
        name,
        path: rel,
        size: stat.size,
        ext: path.extname(name).slice(1).toLowerCase(),
        modified: stat.mtime,
      });
    } else if (stat.isDirectory() && !name.startsWith('.') && name !== '_site') {
      entries.push(...scanDir(full, base));
    }
  }
  return entries;
}

async function publishStatic(inputDir, outputDir) {
  const outDir = outputDir || path.join(inputDir, '_site');
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  const entries = scanDir(inputDir, inputDir);

  // Copy all files to _site
  for (const entry of entries) {
    const src = path.join(inputDir, entry.path);
    const dest = path.join(outDir, entry.path);
    const destDir = path.dirname(dest);
    if (!fs.existsSync(destDir)) {
      fs.mkdirSync(destDir, { recursive: true });
    }
    fs.copyFileSync(src, dest);
  }

  // Build index
  const sprintName = path.basename(path.resolve(inputDir));
  const cards = entries.map((e) => `
    <div class="card">
      <a href="${e.path}">${e.name}</a>
      <div class="meta">${e.ext.toUpperCase()} &middot; ${formatBytes(e.size)}</div>
    </div>`).join('\n');

  const html = TEMPLATE(`Sprint: ${sprintName}`, cards);
  fs.writeFileSync(path.join(outDir, 'index.html'), html, 'utf-8');

  return {
    outputPath: outDir,
    message: `Static site written to ${outDir} (${entries.length} artifacts)`,
  };
}

module.exports = {
  name: 'static',
  description: 'Generate a static site from sprint outputs',
  publish: publishStatic,
};
