/**
 * mill format: sql
 *
 * Converts compilation.json to SQL CREATE TABLE + INSERT statements.
 * Compatible with SQLite and PostgreSQL.
 * Zero dependencies — node built-in only.
 */

export const name = 'sql';
export const extension = '.sql';
export const mimeType = 'application/sql; charset=utf-8';
export const description = 'SQL schema and INSERT statements for claims data';

/**
 * Convert a compilation object to SQL statements.
 * @param {object} compilation - The compilation.json content
 * @returns {string} SQL output
 */
export function convert(compilation) {
  const claims = compilation.claims || [];
  const meta = compilation.meta || {};
  const certificate = compilation.certificate || {};

  const lines = [];

  lines.push('-- Auto-generated by mill sql format');
  if (meta.sprint) lines.push(`-- Sprint: ${meta.sprint}`);
  if (certificate.compiled_at) lines.push(`-- Compiled: ${certificate.compiled_at}`);
  lines.push('');

  // Claims table
  lines.push('CREATE TABLE IF NOT EXISTS claims (');
  lines.push('  id TEXT PRIMARY KEY,');
  lines.push('  type TEXT,');
  lines.push('  content TEXT,');
  lines.push('  evidence_tier TEXT,');
  lines.push('  status TEXT,');
  lines.push('  confidence REAL,');
  lines.push('  source TEXT,');
  lines.push('  tags TEXT,');
  lines.push('  created TEXT');
  lines.push(');');
  lines.push('');

  // Conflicts table
  lines.push('CREATE TABLE IF NOT EXISTS conflicts (');
  lines.push('  id INTEGER PRIMARY KEY AUTOINCREMENT,');
  lines.push('  claim_ids TEXT,');
  lines.push('  description TEXT,');
  lines.push('  resolution TEXT');
  lines.push(');');
  lines.push('');

  // Insert claims
  if (claims.length > 0) {
    lines.push('-- Claims');
    for (const claim of claims) {
      const id = esc(claim.id || '');
      const type = esc(claim.type || '');
      const content = esc(claim.content || claim.text || '');
      const evidenceTier = esc(extractTier(claim));
      const status = esc(claim.status || '');
      const confidence = claim.confidence != null ? String(claim.confidence) : 'NULL';
      const source = esc(extractSource(claim));
      const tags = esc(Array.isArray(claim.tags) ? claim.tags.join(',') : '');
      const created = esc(claim.created || '');

      lines.push(
        `INSERT INTO claims VALUES ('${id}', '${type}', '${content}', '${evidenceTier}', '${status}', ${confidence}, '${source}', '${tags}', '${created}');`
      );
    }
    lines.push('');
  }

  // Insert conflicts
  const conflicts = compilation.conflicts || [];
  if (conflicts.length > 0) {
    lines.push('-- Conflicts');
    for (const conflict of conflicts) {
      const claimIds = esc(Array.isArray(conflict.ids) ? conflict.ids.join(',') : '');
      const description = esc(conflict.description || conflict.reason || '');
      const resolution = esc(conflict.resolution || '');

      lines.push(
        `INSERT INTO conflicts (claim_ids, description, resolution) VALUES ('${claimIds}', '${description}', '${resolution}');`
      );
    }
    lines.push('');
  }

  return lines.join('\n');
}

function esc(value) {
  if (value == null) return '';
  return String(value).replace(/'/g, "''");
}

function extractTier(claim) {
  if (typeof claim.evidence === 'string') return claim.evidence;
  if (typeof claim.evidence === 'object' && claim.evidence !== null) {
    return claim.evidence.tier || '';
  }
  return claim.evidence_tier || '';
}

function extractSource(claim) {
  if (typeof claim.source === 'string') return claim.source;
  if (typeof claim.source === 'object' && claim.source !== null) {
    return claim.source.origin || claim.source.artifact || '';
  }
  if (typeof claim.evidence === 'object' && claim.evidence?.source) {
    return claim.evidence.source;
  }
  return '';
}
