/**
 * mill format: typescript-defs
 *
 * Converts compilation.json to TypeScript .d.ts definitions.
 * Derives union types from actual claim data values.
 * Zero dependencies — node built-in only.
 */

export const name = "typescript-defs";
export const extension = ".d.ts";
export const mimeType = "text/plain; charset=utf-8";
export const description =
  "TypeScript type definitions derived from compilation data";

/**
 * Convert a compilation object to TypeScript .d.ts definitions.
 * @param {object} compilation - The compilation.json content
 * @returns {string} TypeScript definition output
 */
export function convert(compilation) {
  const claims = compilation.claims || [];
  const meta = compilation.meta || {};
  const conflicts = compilation.conflicts || [];
  const certificate = compilation.certificate || {};

  const claimTypes = uniqueSorted(claims.map((c) => c.type).filter(Boolean));
  const evidenceTiers = uniqueSorted(
    claims
      .map((c) => {
        if (typeof c.evidence === "string") return c.evidence;
        return c.evidence?.tier ?? c.evidence_tier ?? null;
      })
      .filter(Boolean),
  );
  const statuses = uniqueSorted(claims.map((c) => c.status).filter(Boolean));

  const lines = [];

  lines.push("// Auto-generated by mill typescript-defs format");
  lines.push("// Derived from compilation data — do not edit manually");
  lines.push("");

  // ClaimType union
  lines.push(`export type ClaimType = ${unionType(claimTypes)};`);
  lines.push("");

  // EvidenceTier union
  lines.push(`export type EvidenceTier = ${unionType(evidenceTiers)};`);
  lines.push("");

  // ClaimStatus union
  lines.push(`export type ClaimStatus = ${unionType(statuses)};`);
  lines.push("");

  // Evidence interface
  lines.push("export interface Evidence {");
  lines.push("  tier: EvidenceTier;");
  lines.push("  source?: string;");
  lines.push("}");
  lines.push("");

  // Source interface
  lines.push("export interface ClaimSource {");
  lines.push("  origin?: string;");
  lines.push("  artifact?: string;");
  lines.push("}");
  lines.push("");

  // Claim interface
  lines.push("export interface Claim {");
  lines.push("  id: string;");
  lines.push("  type: ClaimType;");
  lines.push("  content: string;");
  lines.push("  evidence: EvidenceTier | Evidence;");
  lines.push("  status: ClaimStatus;");
  lines.push("  confidence?: number;");
  lines.push("  source?: string | ClaimSource;");
  lines.push("  tags?: string[];");
  lines.push("  created?: string;");
  lines.push("}");
  lines.push("");

  // Meta interface
  lines.push("export interface Meta {");
  lines.push("  sprint?: string;");
  lines.push("  question?: string;");
  lines.push("  audience?: string;");
  for (const key of Object.keys(meta)) {
    if (!["sprint", "question", "audience"].includes(key)) {
      lines.push(`  ${sanitizeKey(key)}?: ${inferTsType(meta[key])};`);
    }
  }
  lines.push("}");
  lines.push("");

  // Conflict interface
  lines.push("export interface Conflict {");
  lines.push("  ids?: string[];");
  lines.push("  description?: string;");
  lines.push("  reason?: string;");
  lines.push("  resolution?: string;");
  lines.push("}");
  lines.push("");

  // Certificate interface
  lines.push("export interface Certificate {");
  lines.push("  compiled_at?: string;");
  lines.push("  sha256?: string;");
  lines.push("  claim_count?: number;");
  for (const key of Object.keys(certificate)) {
    if (!["compiled_at", "sha256", "claim_count"].includes(key)) {
      lines.push(`  ${sanitizeKey(key)}?: ${inferTsType(certificate[key])};`);
    }
  }
  lines.push("}");
  lines.push("");

  // Compilation interface
  lines.push("export interface Compilation {");
  lines.push("  meta: Meta;");
  lines.push("  claims: Claim[];");
  lines.push("  conflicts: Conflict[];");
  lines.push("  certificate: Certificate;");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function uniqueSorted(arr) {
  return [...new Set(arr)].sort();
}

function unionType(values) {
  if (values.length === 0) return "string";
  return values.map((v) => `'${v}'`).join(" | ");
}

function sanitizeKey(key) {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `'${key}'`;
}

function inferTsType(value) {
  if (value === null || value === undefined) return "unknown";
  if (typeof value === "number") return "number";
  if (typeof value === "boolean") return "boolean";
  if (typeof value === "string") return "string";
  if (Array.isArray(value)) return "unknown[]";
  return "Record<string, unknown>";
}
