/**
 * mill format: yaml
 *
 * Converts compilation.json to YAML output.
 * Simple JSON-to-YAML serializer — handles objects, arrays, strings,
 * numbers, booleans, and nulls. No external dependencies.
 * Zero dependencies — node built-in only.
 */

export const name = 'yaml';
export const extension = '.yaml';
export const mimeType = 'text/yaml; charset=utf-8';
export const description = 'YAML serialization of compilation data';

/**
 * Convert a compilation object to YAML.
 * @param {object} compilation - The compilation.json content
 * @returns {string} YAML output
 */
export function convert(compilation) {
  const lines = [];
  lines.push('# Auto-generated by mill yaml format');
  lines.push('');
  lines.push(toYaml(compilation, 0));
  return lines.join('\n');
}

function toYaml(value, indent) {
  if (value === null || value === undefined) {
    return 'null';
  }
  if (typeof value === 'boolean') {
    return value ? 'true' : 'false';
  }
  if (typeof value === 'number') {
    return String(value);
  }
  if (typeof value === 'string') {
    return yamlString(value, indent);
  }
  if (Array.isArray(value)) {
    return yamlArray(value, indent);
  }
  if (typeof value === 'object') {
    return yamlObject(value, indent);
  }
  return String(value);
}

function yamlString(str, indent) {
  // Use block scalar for multi-line strings
  if (str.includes('\n')) {
    const pad = ' '.repeat(indent + 2);
    const indented = str.split('\n').map(line => pad + line).join('\n');
    return '|\n' + indented;
  }
  // Quote if the string contains special YAML characters or could be misinterpreted
  if (needsQuoting(str)) {
    return "'" + str.replace(/'/g, "''") + "'";
  }
  return str;
}

function needsQuoting(str) {
  if (str === '') return true;
  if (str === 'true' || str === 'false' || str === 'null' || str === 'yes' || str === 'no') return true;
  if (/^[0-9]/.test(str) && !isNaN(Number(str))) return true;
  if (/[:{}\[\],&*?|>!%#@`"']/.test(str)) return true;
  if (/^\s|\s$/.test(str)) return true;
  if (str.startsWith('- ') || str.startsWith('? ')) return true;
  return false;
}

function yamlArray(arr, indent) {
  if (arr.length === 0) return '[]';
  const pad = ' '.repeat(indent);
  const items = [];
  for (const item of arr) {
    if (item !== null && typeof item === 'object' && !Array.isArray(item)) {
      // Object items: first key on same line as -, rest indented
      const keys = Object.keys(item);
      if (keys.length === 0) {
        items.push(pad + '- {}');
      } else {
        const firstKey = keys[0];
        const firstVal = toYaml(item[firstKey], indent + 4);
        const firstLine = isScalar(item[firstKey])
          ? `${pad}- ${firstKey}: ${firstVal}`
          : `${pad}- ${firstKey}:\n${indentBlock(firstVal, indent + 4)}`;
        const rest = keys.slice(1).map(key => {
          const val = toYaml(item[key], indent + 4);
          if (isScalar(item[key])) {
            return `${pad}  ${key}: ${val}`;
          }
          return `${pad}  ${key}:\n${indentBlock(val, indent + 4)}`;
        });
        items.push([firstLine, ...rest].join('\n'));
      }
    } else if (Array.isArray(item)) {
      const nested = toYaml(item, indent + 2);
      items.push(`${pad}-\n${indentBlock(nested, indent + 2)}`);
    } else {
      items.push(`${pad}- ${toYaml(item, indent + 2)}`);
    }
  }
  return '\n' + items.join('\n');
}

function yamlObject(obj, indent) {
  const keys = Object.keys(obj);
  if (keys.length === 0) return '{}';
  const pad = ' '.repeat(indent);
  const entries = [];
  for (const key of keys) {
    const val = obj[key];
    const yamlKey = needsQuoting(key) ? `'${key.replace(/'/g, "''")}'` : key;
    if (isScalar(val)) {
      entries.push(`${pad}${yamlKey}: ${toYaml(val, indent + 2)}`);
    } else {
      const nested = toYaml(val, indent + 2);
      if (nested.startsWith('\n')) {
        entries.push(`${pad}${yamlKey}:${nested}`);
      } else {
        entries.push(`${pad}${yamlKey}:\n${indentBlock(nested, indent + 2)}`);
      }
    }
  }
  return '\n' + entries.join('\n');
}

function isScalar(value) {
  return value === null || value === undefined ||
    typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean';
}

function indentBlock(text, indent) {
  const pad = ' '.repeat(indent);
  return text.split('\n').map(line => {
    if (line.trim() === '') return '';
    // Only add padding if the line doesn't already have it
    if (line.startsWith(pad)) return line;
    return pad + line;
  }).join('\n');
}
